### ISSUE TITLE
MultiCraft_game ToDo

### ISSUE THREAD

**Issue by MoNTE48** [MultiCraft/MultiCraft#15]
5) Luminous stone to make deeper. It creates problems glow under water.
6) Update bone meal https://forum.minetest.net/viewtopic.php?id=5429

**Comment by Monkeyboy2805** [comment]
About 3: just improve mob performance. minecraft itself is fine so you should be too

**Comment by paramat** [comment]
4. The deepest oceans are in mgv5, a depth of y = -256 for luminous stone is enough to always be below mgv5 oceans.

**Comment by paramat** [comment]
> This https://github.com/MultiCraftProject/MultiCraft/blob/master/src/cavegen.h#L24 should be 48 to enable lava in large caves

Actually, don't change this, in MT i have just added 2 new mapgen parameters 'large cave depth' and 'lava depth', so you can keep mapgen code the same as in MT and can set these depths in Lua in your MC subgame.

**Comment by paramat** [comment]
I'll see if i can get bedrock extending through oceans.

**Comment by paramat** [comment]
I discovered your bedrock is not being placed because ymin and ymax are not far enough apart to allow a cluster size of 2, this works with ymax = -62:
```
	minetest.register_ore({
		ore_type       = "scatter",
		ore            = "default:bedrock",
		wherein        = {"default:stone"},
		clust_scarcity = 1 * 1 * 1,
		clust_num_ores = 5,
		clust_size     = 2,
		y_min     = -64,
		y_max     = -62,
	})
```
In the screenshot below meselamp is used for testing to be visible underground, you can see that it does not cut through a deep ocean in mgv5.

![screenshot_20170709_194609](https://user-images.githubusercontent.com/3686677/27996690-bfff938e-64df-11e7-888d-7f717880df57.png)

So use:
```
	minetest.register_ore({
		ore_type       = "scatter",
		ore            = "default:bedrock",
		wherein        = {"default:stone", "default:water_source"},
		clust_scarcity = 1 * 1 * 1,
		clust_num_ores = 5,
		clust_size     = 2,
		y_min     = -64,
		y_max     = -62,
	})
```

**Comment by paramat** [comment]
I'll make a PR.

**Comment by paramat** [comment]
PR #83
